project:
  type: website
  output-dir: docs

website:
  title: "Mike Diessner"
  site-url: "http://www.stat.cmu.edu/~ryurko/"
  navbar:
    right:

      - icon: github
        href: https://github.com/mikediessner
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=qSIiHM4AAAAJ&hl=en
      - icon: twitter
        href: https://twitter.com/mikediessner
      - icon: linkedin
        href: https://uk.linkedin.com/in/mikediessner
      - icon: envelope
        href: mailto:m.diessner2@newcastle.ac.uk

format:
  html:
    theme: litera
    toc: true
    font-family: serif



editor: visual

