project:
  type: website
  output-dir: docs

website:
  title: "Mike Diessner"
  favicon: favicon.png
  navbar:
    right:
      - icon: github
        href: https://github.com/mikediessner
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=qSIiHM4AAAAJ&hl=en
      - icon: linkedin
        href: https://uk.linkedin.com/in/mikediessner
      - icon: envelope
        href: mailto:m.diessner2@newcastle.ac.uk

format:
  html:
    theme: litera
    toc: true
    smooth-scroll: true

